# Generated by Django 5.0.7 on 2025-05-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
