# Generated by Django 5.2 on 2026-03-10 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_tokenproxy_alter_inventorycount_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('account_holder', models.CharField(blank=True, default='', max_length=100)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank'), ('EWALLET', 'E-Wallet'), ('QRIS', 'QRIS')], db_index=True, default='BANK', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('bank_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('QRIS', 'QRIS'), ('CARD', 'Card')], db_index=True, default='CASH', max_length=20)),
                ('requires_bank_account', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='pos.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='pos.paymentmethod')),
            ],
            options={
                'ordering': ('paid_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BankLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE_IN', 'Sale Income'), ('DEPOSIT', 'Cash Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('REFUND_OUT', 'Refund Out'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=30)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='pos.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_ledgers', to=settings.AUTH_USER_MODEL)),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_ledgers', to='pos.order')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_ledgers', to='pos.salepayment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
