# Generated by Django 5.2 on 2026-02-13 14:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_tokenproxy_alter_banner_image_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='all_category_icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='all_category_icon'),
        ),
    ]
