# Generated by Django 5.2 on 2026-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_category_name_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cell',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
