# Generated by Django 5.2 on 2026-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_shop_all_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='default_order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKE_OUT', 'Take-Out'), ('DELIVERY', 'Delivery')], db_index=True, default='TAKE_OUT', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKE_OUT', 'Take-Out'), ('DELIVERY', 'Delivery')], db_index=True, default='TAKE_OUT', max_length=20),
        ),
    ]
