# Generated by Django 5.2 on 2026-02-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_order_default_order_type_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='default_order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKE_OUT', 'Take-Out'), ('DELIVERY', 'Delivery')], default='TAKE_OUT', max_length=20),
        ),
    ]
