# Generated by Django 5.2 on 2026-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_order_default_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='default_order_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DINE_IN', 'Dine-In'), ('TAKE_OUT', 'Take-Out'), ('DELIVERY', 'Delivery')], default='TAKE_OUT', max_length=20),
        ),
    ]
