# Generated by Django 5.2 on 2026-03-13 00:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_product_options_category_shop_customer_shop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycount',
            options={'ordering': ('-counted_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreturn',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='counted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorycountitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_count_items', to='pos.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='pos.customer'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='pos.order'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_return_items', to='pos.product'),
        ),
        migrations.AlterField(
            model_name='productreturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['shop', 'is_active'], name='pos_bankacc_shop_id_16aaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['shop', 'bank_name'], name='pos_bankacc_shop_id_b52eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['shop', 'status'], name='pos_invento_shop_id_319109_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['shop', 'counted_at'], name='pos_invento_shop_id_6fe761_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'created_at'], name='pos_order_shop_id_ad948b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'is_paid'], name='pos_order_shop_id_41080f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'default_order_type'], name='pos_order_shop_id_b58808_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['shop', 'returned_at'], name='pos_product_shop_id_1ded0d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['shop', 'created_at'], name='pos_stockmo_shop_id_fa9cca_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['shop', 'movement_type'], name='pos_stockmo_shop_id_327cd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('shop', 'bank_name', 'name'), name='unique_bank_account_name_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountitem',
            constraint=models.UniqueConstraint(fields=('inventory', 'product'), name='unique_product_per_inventory_count'),
        ),
        migrations.AddConstraint(
            model_name='productreturnitem',
            constraint=models.UniqueConstraint(fields=('product_return', 'product'), name='unique_product_per_return'),
        ),
    ]
