# Generated by Django 5.2 on 2026-03-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_shop_options_shop_backend_url_shop_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('name',), 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='pos.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('shop', 'code'), name='unique_payment_method_code_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_payment_method_name_per_shop'),
        ),
    ]
