# Generated by Django 5.2 on 2026-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_customer_points_product_sku_alter_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(
                max_length=32,
                blank=True,
                null=True,              
                db_index=True,
                help_text='Auto generated invoice number. Example: INV000000000123',
            ),
        ),
    ]

