# Generated by Django 5.2 on 2026-03-13 15:55

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_shop_options_paymentmethod_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': 'Platform Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pos.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShopStaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Staff',
                'verbose_name_plural': 'Shop Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pos.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
