# Generated by Django 5.2 on 2026-03-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_platformuser_shopstaffuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier')], db_index=True, default='cashier', max_length=20),
        ),
    ]
