# Generated by Django 5.2 on 2026-02-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_order_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(db_index=True, editable=False, help_text='Auto generated invoice number. Example: INV000000000123', max_length=32, unique=True),
        ),
    ]
