# Generated by Django 5.2 on 2026-02-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_alter_order_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=20),
        ),
    ]
