# Generated by Django 5.2 on 2026-03-15 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pos', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='banner',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='pos.shop'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inventorycountitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_items', to='pos.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.unit'),
        ),
        migrations.AlterField(
            model_name='productreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_return_items', to='pos.product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='code',
            field=models.CharField(max_length=30, unique=True, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pos.product'),
        ),
        migrations.AddIndex(
            model_name='bankledger',
            index=models.Index(fields=['bank_account', 'created_at'], name='pos_bankled_bank_ac_f354cf_idx'),
        ),
        migrations.AddIndex(
            model_name='bankledger',
            index=models.Index(fields=['bank_account', 'transaction_type'], name='pos_bankled_bank_ac_c0c11a_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['shop', 'active'], name='pos_banner_shop_id_be25a4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['shop', 'name'], name='pos_categor_shop_id_4ffa99_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'name'], name='pos_custome_shop_id_62df85_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['shop', 'role'], name='pos_customu_shop_id_23120b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['shop', 'date'], name='pos_expense_shop_id_05bf40_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='pos_orderit_order_i_0232e0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['shop', 'payment_type'], name='pos_payment_shop_id_a6661f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['shop', 'is_active'], name='pos_payment_shop_id_e9b2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['order', 'paid_at'], name='pos_salepay_order_i_74a2be_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active', 'name'], name='pos_shop_is_acti_22184b_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['code'], name='pos_shop_code_eccc64_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug'], name='pos_shop_slug_63e3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['shop', 'adjusted_at'], name='pos_stockad_shop_id_2bdc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['shop', 'name'], name='pos_supplie_shop_id_2044fd_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['shop', 'name'], name='pos_unit_shop_id_910311_idx'),
        ),
    ]
