# Generated by Django 5.2 on 2026-02-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], db_index=True, default='cashier', max_length=20),
        ),
    ]
