# Generated by Django 5.2 on 2026-03-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_customuser_options_banner_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='pos.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
