# Generated by Django 5.2 on 2026-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_banner_shop_alter_shop_code_alter_shop_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase_invoice_per_shop_supplier',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_id', ''), _negated=True), fields=('shop', 'invoice_id'), name='unique_purchase_invoice_per_shop_when_present'),
        ),
    ]
