# Generated by Django 5.2 on 2026-03-16 13:03

import django.db.models.deletion
import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_remove_purchase_unique_purchase_invoice_per_shop_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_dine_in', models.BooleanField(default=False)),
                ('enable_takeaway', models.BooleanField(default=False)),
                ('enable_delivery', models.BooleanField(default=False)),
                ('enable_table_number', models.BooleanField(default=False)),
                ('enable_barcode_scan', models.BooleanField(default=True)),
                ('enable_customer_points', models.BooleanField(default=True)),
                ('enable_split_payment', models.BooleanField(default=True)),
                ('enable_service_fee', models.BooleanField(default=False)),
                ('enable_mechanic', models.BooleanField(default=False)),
                ('enable_vehicle_info', models.BooleanField(default=False)),
                ('show_product_images_in_pos', models.BooleanField(default=True)),
                ('use_grid_pos_layout', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Feature',
                'verbose_name_plural': 'Shop Features',
            },
            bases=(pos.models.CleanSaveMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('menu', 'Menu'), ('service', 'Service'), ('sparepart', 'Sparepart')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('retail', 'Retail'), ('workshop', 'Workshop')], db_index=True, default='retail', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='default_order_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DINE_IN', 'Dine-In'), ('TAKE_OUT', 'Take-Out'), ('DELIVERY', 'Delivery')], db_index=True, default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DINE_IN', 'Dine-In'), ('TAKE_OUT', 'Take-Out'), ('DELIVERY', 'Delivery')], db_index=True, default='GENERAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'item_type'], name='pos_product_shop_id_07b2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['business_type'], name='pos_shop_busines_4ccdb4_idx'),
        ),
        migrations.AddField(
            model_name='shopfeature',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pos.shop'),
        ),
    ]
