# Generated by Django 5.2 on 2026-03-29 15:44

import django.db.models.deletion
import django.utils.timezone
import pos.models_backup
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_shopfeature_product_item_type_product_track_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], db_index=True, default='running', max_length=20)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=150)),
                ('include_database', models.BooleanField(default=True)),
                ('include_media', models.BooleanField(default=False)),
                ('include_users', models.BooleanField(default=False)),
                ('include_settings', models.BooleanField(default=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=pos.models_backup.backup_file_upload_to)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_size_label', models.CharField(blank=True, default='', max_length=50)),
                ('file_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backup_histories', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_histories', to='pos.shop')),
            ],
            options={
                'verbose_name': 'Backup History',
                'verbose_name_plural': 'Backup Histories',
                'ordering': ('-started_at', '-id'),
            },
            bases=(pos.models_backup.CleanSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='daily', max_length=20)),
                ('backup_time', models.TimeField(default='23:30')),
                ('keep_last', models.PositiveIntegerField(default=10)),
                ('include_media', models.BooleanField(default=True)),
                ('include_users', models.BooleanField(default=True)),
                ('include_settings', models.BooleanField(default=True)),
                ('default_restore_mode', models.CharField(choices=[('full', 'Full Restore'), ('master', 'Master Data Only')], default='full', max_length=20)),
                ('last_auto_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_manual_backup_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_setting', to='pos.shop')),
            ],
            options={
                'verbose_name': 'Backup Setting',
                'verbose_name_plural': 'Backup Settings',
            },
            bases=(pos.models_backup.CleanSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RestoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_mode', models.CharField(choices=[('full', 'Full Restore'), ('master', 'Master Data Only')], db_index=True, default='full', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], db_index=True, default='running', max_length=20)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=150)),
                ('restore_file', models.FileField(blank=True, null=True, upload_to=pos.models_backup.restore_file_upload_to)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_histories', to='pos.backuphistory')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_restores', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_histories', to='pos.shop')),
            ],
            options={
                'verbose_name': 'Restore History',
                'verbose_name_plural': 'Restore Histories',
                'ordering': ('-started_at', '-id'),
            },
            bases=(pos.models_backup.CleanSaveMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='backuphistory',
            index=models.Index(fields=['shop', 'status'], name='pos_backuph_shop_id_9ee0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='backuphistory',
            index=models.Index(fields=['shop', 'backup_type'], name='pos_backuph_shop_id_fe8f97_idx'),
        ),
        migrations.AddIndex(
            model_name='backuphistory',
            index=models.Index(fields=['shop', 'started_at'], name='pos_backuph_shop_id_c53ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='backuphistory',
            index=models.Index(fields=['shop', 'completed_at'], name='pos_backuph_shop_id_039c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='backupsetting',
            index=models.Index(fields=['enabled', 'frequency'], name='pos_backups_enabled_c34e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='restorehistory',
            index=models.Index(fields=['shop', 'status'], name='pos_restore_shop_id_8cb6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='restorehistory',
            index=models.Index(fields=['shop', 'restore_mode'], name='pos_restore_shop_id_235d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='restorehistory',
            index=models.Index(fields=['shop', 'started_at'], name='pos_restore_shop_id_40c5f3_idx'),
        ),
    ]
