# Generated by Django 5.2 on 2026-03-29 16:29

import django.db.models.deletion
import pos.models_import
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_backuphistory_backupsetting_restorehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pos.models_import.import_file_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='pos.shop')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ('-created_at', '-id'),
            },
            bases=(pos.models_import.CleanSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100)),
                ('row_number', models.PositiveIntegerField()),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='pos.importjob')),
            ],
            options={
                'verbose_name': 'Import Row Error',
                'verbose_name_plural': 'Import Row Errors',
                'ordering': ('sheet_name', 'row_number', 'id'),
            },
            bases=(pos.models_import.CleanSaveMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['shop', 'status'], name='pos_importj_shop_id_9834b3_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['shop', 'created_at'], name='pos_importj_shop_id_a8779b_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['shop', 'validated_at'], name='pos_importj_shop_id_a80b64_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['shop', 'completed_at'], name='pos_importj_shop_id_6bd584_idx'),
        ),
        migrations.AddIndex(
            model_name='importrowerror',
            index=models.Index(fields=['import_job', 'sheet_name'], name='pos_importr_import__f91394_idx'),
        ),
        migrations.AddIndex(
            model_name='importrowerror',
            index=models.Index(fields=['import_job', 'row_number'], name='pos_importr_import__af672c_idx'),
        ),
    ]
