# Generated by Django 5.2 on 2026-04-11 17:38

import django.db.models.deletion
import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_alter_banner_image_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('location', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='pos.shop')),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['shop', 'name'], name='pos_warehou_shop_id_e5a506_idx'), models.Index(fields=['shop', 'code'], name='pos_warehou_shop_id_0442b6_idx'), models.Index(fields=['shop', 'is_active'], name='pos_warehou_shop_id_28d48d_idx'), models.Index(fields=['shop', 'is_default'], name='pos_warehou_shop_id_49bda4_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'name'), name='unique_warehouse_name_per_shop'), models.UniqueConstraint(fields=('shop', 'code'), name='unique_warehouse_code_per_shop')],
            },
            bases=(pos.models.CleanSaveMixin, models.Model),
        ),
    ]
