# Generated by Django 5.2 on 2026-04-11 17:53

import django.db.models.deletion
import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='pos.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='pos.shop')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pos.warehouse')),
            ],
            options={
                'ordering': ('warehouse', 'product', 'id'),
                'indexes': [models.Index(fields=['shop', 'warehouse'], name='pos_warehou_shop_id_20e07d_idx'), models.Index(fields=['shop', 'product'], name='pos_warehou_shop_id_d47b77_idx'), models.Index(fields=['shop', 'quantity'], name='pos_warehou_shop_id_b33252_idx'), models.Index(fields=['shop', 'min_stock'], name='pos_warehou_shop_id_92059b_idx')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_product_per_warehouse')],
            },
            bases=(pos.models.CleanSaveMixin, models.Model),
        ),
    ]
