# Generated by Django 5.2 on 2026-04-11 18:04

import django.db.models.deletion
import pos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_warehousestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('ADJUSTMENT', 'Adjustment'), ('COUNT', 'Inventory Count'), ('PURCHASE', 'Purchase'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='pos.warehouse')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='pos.shop')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='pos.warehouse')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
            bases=(pos.models.CleanSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_items', to='pos.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.stocktransfer')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(pos.models.CleanSaveMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['shop', 'status'], name='pos_stocktr_shop_id_a1663b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['shop', 'created_at'], name='pos_stocktr_shop_id_648111_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['shop', 'reference_no'], name='pos_stocktr_shop_id_d5f8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferitem',
            index=models.Index(fields=['transfer', 'product'], name='pos_stocktr_transfe_003cc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'product'), name='unique_product_per_stock_transfer'),
        ),
    ]
