"""
Django settings for mypos project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*1-$iq=etsqtx$pk0(aw-k+mq-o0imul3$umeu*$$#i@zskb%e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_TRUSTED_ORIGINS = [
    "https://mypos-production.up.railway.app",
]

ALLOWED_HOSTS = ["mypos-production.up.railway.app", "localhost", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'pos',
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

if os.getenv('RAILWAY_STATIC_URL'):
    STATIC_URL = os.getenv('RAILWAY_STATIC_URL')

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'mypos.urls'

AUTH_USER_MODEL = 'pos.CustomUser'
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
#     'django.contrib.auth.backends.AllowAllUsersModelBackend',  # Allow all users to authenticate
# ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pos.context_processors.user_role_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mypos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#Konfigurasaun Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "MyPOS Admin",
    "site_header": "MyPOS Admin Panel",
    "welcome_sign": "Selamat Datang di MyPOS",
    "site_brand": "MyPOS",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "pos.Customer": "fas fa-user",
        "pos.Supplier": "fas fa-users-cog",
        "pos.Category": "fas fa-boxes",
        "pos.Unit": "fas fa-balance-scale",
        "pos.Product": "fas fa-box-open",
        "pos.Order": "fas fa-shopping-cart",
        "pos.Expense": "fas fa-coins",
        "pos.Shop": "fas fa-store",
        "auth.User": "fas fa-user-shield",
    },
    "custom_links": {
    "pos": [
        {
            "name": "Sales Report",
            "url": "/reports/sales/",
            "icon": "fas fa-chart-line",
            "permissions": ["pos.view_order"]
        },
        {
            "name": "Expense Report",
            "url": "/reports/expense/",
            "icon": "fas fa-file-invoice-dollar",
            "permissions": ["pos.view_expense"]
        },
        {
            "name": "Sales Chart",
            "url": "/reports/sales-chart/",
            "icon": "fas fa-chart-pie",
            "permissions": ["pos.view_order"]
        },
        {
            "name": "Expense Chart",
            "url": "/reports/expense-chart/",
            "icon": "fas fa-chart-area",
            "permissions": ["pos.view_expense"]
        },
      ]
    },
    "order_with_respect_to": [
    "pos.Customer",
    "pos.Supplier",
    "pos.Product",
    "pos.Order",
    "pos.OrderItem",
    "pos.Expense",
    "pos.Category",
    "pos.Unit",
    "pos.Shop",
    "auth.Group",
    "auth.User"
],
"hide_apps": ["auth"],
"hide_models": ["auth.User", "auth.Group"],
"show_ui_builder": False,
"show_ui_builder": False,
# "custom_apps": {
#     "auth": {
#         "name": "Admin Users",
#         "icon": "fas fa-user-shield"
#     }
# },
    "topmenu_links": [
        {"name": "Dashboard", "url": "/admin", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"name": "Logout", "url": "/admin/logout/", "new_window": False},
    ],
    "side_menu": [
    {"app": "pos", "label": "Customers", "models": ["pos.Customer"]},
    {"app": "pos", "label": "Suppliers", "models": ["pos.Supplier"]},
    {"app": "pos", "label": "Products Category", "models": ["pos.Category"]},
    {"app": "pos", "label": "Products", "models": ["pos.Product"]},
    {"app": "pos", "label": "Orders", "models": ["pos.Order"]},
    {"app": "pos", "label": "Expense", "models": ["pos.Expense"]},
    {
        "label": "Reports",
        "icon": "fas fa-chart-line",
        "models": [
            {"name": "Sales Report", "url": "/reports/sales/"},
            {"name": "Expense Report", "url": "/reports/expense/"},
            {"name": "Sales Chart", "url": "/reports/sales-chart/"},
            {"name": "Expense Chart", "url": "/reports/expense-chart/"},
        ]
    },
    {
        "label": "Settings",
        "icon": "fas fa-cogs",
        "models": [
            "pos.Shop",
            "pos.Unit",
        ]
    },
    {
        "app": "auth",
        "label": "Admin Users",
        "icon": "fas fa-user-shield",
        "models": ["auth.Group", "auth.User"]
    }
 ],
}

